# Generated by Django 4.0.4 on 2022-06-01 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentattendenceblock_studentattendences_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='degree',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 45, 21, 714333)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 45, 21, 714333)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 45, 21, 715331)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 45, 21, 715331)),
        ),
    ]
