# Generated by Django 4.0.4 on 2022-06-01 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_faculty_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 53, 18, 443491)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 53, 18, 443491)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 53, 18, 444488)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 2, 4, 53, 18, 444488)),
        ),
        migrations.AlterField(
            model_name='studentattendences',
            name='student_usn',
            field=models.CharField(max_length=30),
        ),
    ]
