# Generated by Django 4.0.4 on 2022-06-08 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_faculty_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='phome',
            field=models.CharField(choices=[('8197424203', '8197424203'), ('8747972557', '8747972557'), ('9663172677', '9663172677')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='phome',
            field=models.CharField(choices=[('8197424203', '8197424203'), ('8747972557', '8747972557'), ('9663172677', '9663172677')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 0, 40, 51, 165515)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 0, 40, 51, 165515)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 0, 40, 51, 166513)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 0, 40, 51, 166513)),
        ),
        migrations.AlterField(
            model_name='studentattendenceblock',
            name='subject',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('BEEE', 'BEEE'), ('ENGLISH', 'ENGLISH'), ('SCIENCE', 'SCIENCE')], max_length=30),
        ),
        migrations.AlterField(
            model_name='studentattendences',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='studentattendences',
            name='subject',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('BEEE', 'BEEE'), ('ENGLISH', 'ENGLISH'), ('SCIENCE', 'SCIENCE')], max_length=30),
        ),
    ]
