# Generated by Django 4.0.4 on 2022-06-09 17:00

import datetime
from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_rename_phome_faculty_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendences',
            name='attendenceBlock',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='studentattendences',
            name='previous_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 22, 30, 39, 78061)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 22, 30, 39, 78061)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='phone',
            field=models.CharField(choices=[('8197424203', '8197424203'), ('8747972557', '8747972557'), ('9663172677', '9663172677'), ('9986168736', '9986168736')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 22, 30, 39, 79059)),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_joining',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 9, 22, 30, 39, 79059)),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(choices=[('8197424203', '8197424203'), ('8747972557', '8747972557'), ('9663172677', '9663172677'), ('9986168736', '9986168736')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentattendenceblock',
            name='attendenceBlock',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
